### ISSUE TITLE
Tests in abstract classes are not discovered.

### ISSUE THREAD

**Issue by dmeagor** [CodeConnect/AliveFeedback#25] opened 2015-07-23 13:22 UTC
Hi

Whilst the extension is working for static classes I am unable to get it to detect the solutions nunit tests.

The tests call the target method using this syntax.  

```
var result = CallAction<JsonResult>(x => x.GetProjectList());
```

Apparently there is no easy way to change this as CallAction runs action inside of UnitOfWork and UnitOfWork itself uses delegates.

**Comment by AmadeusW** [comment] 2015-07-23 18:54
Hi @dmeagor 

I created a scenario where a simple action is defined using a lambda. Alive discovered the mapping from the test case to the specified method, so let's dig deeper into where the issue is.

Alive writes to the _Output_ window when it encounters exceptions. Can you tell us if you see any exceptions, and what are they? Also, are you using Rhino-mocks framework?

The screenshot shows the _Output_ window. To see Alive's output, go to `Debug > Windows > Output` and then select `Alive` from the _Show output from_ drop-down.

![screenshot](http://i.gyazo.com/95021d3c1622135102d7bbb3d7cab7a3.png)

**Comment by dmeagor** [comment] 2015-07-24 12:49
Looks like some errors...

```
[Performance, TestDiscovery, Message] 2015-07-24 12:46:23Z - Test discovery - 138 ms. 
[Performance, TestDiscovery, Message] 2015-07-24 12:46:26Z - Method rewriting - 2709 ms. 
[Performance, TestDiscovery, Message] 2015-07-24 12:46:31Z - Building rewritten solution - 4912 ms. 
[TestDiscovery, Message] Running tests in FreeSurvey.Core.TestHelpers... 
[Error, TestDiscovery] Error running test case TestAutoMapperMappings 
[Error, TestDiscovery]  -> Cannot create an abstract class. 
[TestDiscovery, Message] Running tests in FreeSurvey.Web.Tests... 
[TestDiscovery, Message] Running tests in FreeSurvey.Core.Tests... 
[Performance, TestDiscovery, Message] 2015-07-24 12:46:32Z - Test case invocation - 1737 ms. 
[TestDiscovery, Message] Alive finished test discovery. 
```

**Comment by JoshVarty** [comment] 2015-07-24 18:51
Thanks @dmeagor we're going to take a look at this.

**Comment by AmadeusW** [comment] 2015-10-01 00:43
@dmeagor does the issue still persist in your project?

**Comment by AmadeusW** [comment] 2015-10-27 21:02
Closing - Alive supports test cases defined in abstract classes since version 0.6

**Closed as completed by AmadeusW** 2015-10-27 21:02 UTC
Labels: bug
