### ISSUE TITLE
Add Unity3d support

### ISSUE THREAD

**Issue by heyJordanParker** [CodeConnect/AliveFeedback#98] opened 2016-02-29 01:55 UTC
The plugin fails to work with Unity3d components due to error CS0619 "Component is obsolete".

**Comment by JoshVarty** [comment] 2016-02-29 02:22
Can you give us some sample code perhaps? We've never worked with Unity3D before.

Are you using VS2015?

**Comment by heyJordanParker** [comment] 2016-02-29 12:08
This is the original issue:
CS0619 Obsolete method/function. 

![2016-02-29_14h00_35](https://cloud.githubusercontent.com/assets/7506303/13393937/3dbb3366-deed-11e5-8e9a-41568071d68c.png)

This happens with some tinkering of the logic:

![2016-02-29_14h02_30](https://cloud.githubusercontent.com/assets/7506303/13393972/86256a18-deed-11e5-8c3f-e4c0ca09e07e.png)

The first one could be resolved by blacklisting some DLLs to be parsed. 
The second one is hackable by reflection - by overriding the ToString method ( Even though I'm not perfectly sure what causes the issue in it to begin with ), so I can find a way around that.

PS: It is weird that the parser hits the obsolete errors since their code has never been called. This might occur in other DLLs, too.

**Comment by AmadeusW** [comment] 2016-02-29 20:17
The first issue is caused by using obsolete methods. The errors prevent compilation of the entire project. Alive needs to compile the entire project, even if you'd like to investigate just one method. In my research, these errors affect Alive as much as they affect standard Visual Studio compilation. They are resolved by correcting obsolete methods.

The second one is an issue with Alive, and generally any tool that attempts to use namespace `UnityEngine` outside of Unity.

> The Unity transport layer currently cannot be used outside of the Unity Engine. There are plans for a separate independent UNet DLL with a C# API in a future release for applications like this. 
> - from [Unity forums](http://forum.unity3d.com/threads/networkserver-in-console-application.362012/)

If I understand this correctly, Unity is running in **mono** environment, and Alive (running in **CLR**) is unable to access classes from `UnityEngine`. Perhaps we can circumvent this if we run Alive in mono/unity environment... _But this is highly hypothetical and appears that it would come with its own set of issues._

This means that currently Alive can only launch unity code via unit tests that mock game objects. Alive will break when your code touches anything in `UnityEngine`. In your case, it looks like the `ToString` of `fetchedTransform` is either defined in `UnityEngine` namespace, or itself invokes code defined in `UnityEngine` namespace.

You said that this is hackable by reflection - do you have any code samples of this?

**Comment by heyJordanParker** [comment] 2016-02-29 23:06
If I understood correctly - I'm getting a list of obsolete usages that are anywhere in the UnityEngine.dll and are in fact compilation breaking exceptions. This is highly unlikely.

After decompiling the UnityEngine assembly and doing a good amount of digging - **I couldn't find even a single use** of those obsolete properties in the code inside the assembly. The assembly compiles without any exceptions ( other than those caused by decompilation ).

For some reason, obsolete methods in the assembly that have nothing to do with the current execution path are getting called by the Alive extension. This is an unexpected behavior.

The ToString method error is easier to hack because it is a virtual method thus simpler to override via Reflection. I'll try to make time to test this approach and post it back here soon.

PS: I'm very well aware of the limitations of the engine and tests I write have no problem passing. Every bit of code is executable through Visual Studio, so it's not a problem with the transport layer.

**Comment by AmadeusW** [comment] 2016-03-01 00:41
Okay, that makes sense. Thank you for the details!

We are prototyping a solution that would collect object's properties only on demand, but it might be long ways from implementing it, as we'd likely await on code changes to the Roslyn compiler.

It would be possible to create a workaround that prevents evaluation of faulty properties, but we shy away from patches that correct very specific behavior. Can you help me estimate impact of obsolete properties? Is this a common occurrence in Unity projects?

**Comment by AmadeusW** [comment] 2016-03-01 00:52
It turns out that these properties are marked as [[Obsolete(message, error = true)]](https://msdn.microsoft.com/en-us/library/system.obsoleteattribute%28v=vs.110%29.aspx). 

This means that we're lucky :+1: we need to check if any property is deprecated and if it is, we won't evaluate it.

**Comment by heyJordanParker** [comment] 2016-03-01 02:06
Brilliant!

I've put a few night hours into the ToString solution and you can [somewhat easily modify IL code](http://www.codeproject.com/Articles/463508/NET-CLR-Injection-Modify-IL-Code-during-Run-time) during runtime, but I'd avoid that to keep a decent legacy.

Formatting 3rd party code would rarely make use of overriding the ToString method so are you planning on adding an annotation or another mechanism to do that?

**Comment by AmadeusW** [comment] 2016-03-01 02:32
Ah, modifying IL code is awesome! With [Mono.Cecil](https://github.com/jbevain/cecil) you can also save modified IL code and persist the changes :) This is how we once fixed a bug (invalid cast) in Visual Studio 2013. If you like playing with IL, I highly recommend you check out that library.

Here's how we collect object's properties for what we call "drilldown" (available by clicking the `+` icon in Alive's results): 

We go through type's properties and get their `ToString()`. If any of these properties are `Obsolete`, accessing them to get their `ToString` will cause either a warning or an error (depending on a parameter passed in to `Obsolete` attribute). 

To fix the issue you reported, we need to find attributes of each property and check if any of them are [System.ObsoleteAttribute](https://msdn.microsoft.com/en-us/library/system.obsoleteattribute%28v=vs.110%29.aspx). If that's true, we can ignore this property to avoid the build error. This extra check costs some CPU time, but it fixes a bug and puts the shiny new hardware to use :)

**Comment by AmadeusW** [comment] 2016-03-01 22:06
@jedybg we've patched this issue in [v1.3.12](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.3.12) :sunrise: 
Thank you for letting us know and following up with your findings, it helped a lot. Let us know if you have other issues with Unity or elsewhere!

**Closed as completed by AmadeusW** 2016-03-01 22:06 UTC
Labels: bug, Fixed

**Comment by heyJordanParker** [comment] 2016-03-02 00:46
@AmadeusW Excellent! Keep up the good work - this is by far the most enjoyable way to write code, since the experiments I've messed with after I watched Bret Victor's talk.

**Comment by AmadeusW** [comment] 2016-03-02 00:48
Thanks! I'm glad you like it. He inspired us to build awesome developer with the "Inventing on Principle" talk
